#!/usr/bin/env sh

if [ $# == 0 ]; then
  qemu -kernel src/kernel/kernel
elif [ "$1" == "-boot" ]; then
  echo "Boot from disk image is working in progress."
  #qemu -fda kernel.img
else
  echo "Error: Invalid argument '$1'."
fi
