export AS= i686-elf-as
export ASFLAGS=
export CC= clang
export CFLAGS= -target i686 -std=c99 -fno-builtin -Os -c
export LD= i686-elf-ld
export LDFLAGS=
export OBJCOPY= i686-elf-objcopy
export NASMFLAGS= -f elf
