#!/usr/bin/env sh

name="binutils"
version="2.23.1"
package=$name-$version

wget -c http://ftp.gnu.org/gnu/$name/$package.tar.bz2

tar -xjvf $package.tar.bz2

cd $package

./configure --target=i686-elf --prefix=$HOME
make
make install

cd ..
