#!/usr/bin/env sh

name=binutils
version=2.36.1
package=$name-$version

function fatal {
    echo $1
    exit 1
}

function print_usage {
    fatal "Usage: $(basename $0) -t {i686|mips}"
}

if [ $# -eq 0 ]; then
    print_usage
fi

while getopts ":t:" opt; do
    case $opt in
        t) target_arch=$OPTARG ;;
        \?) print_usage ;;
        :) print_usage ;;
    esac
done

if [ $target_arch != "i686" -a $target_arch != "mips" ]; then
    fatal "Unsupported target archtecture: $target_arch"
fi

target_abi=elf
target=$target_arch-$target_abi

wget -c http://ftp.gnu.org/gnu/$name/$package.tar.bz2

tar -xjf $package.tar.bz2

cd $package

./configure --target=$target --prefix=$HOME/local
make
make install

cd ..
